name: Build and deploy docs
on: [push, pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: cabal-${{ runner.os }}-${{ hashFiles('cabal.project', 'cabal.project.freeze') }}
        restore-keys: cabal-${{ runner.os }}-

    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '9.0'
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y libsecp256k1-0 libsecp256k1-dev
        cabal --version
        ghc --version
        cabal update
        cabal haddock --haddock-hyperlink-source --haddock-quickjump --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs'
        mv dist-newstyle/build/*/*/*/doc/html/ic-hs gh-page
        touch gh-page/.nojekyll
    - name: Deploy to Github Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        BRANCH: gh-pages
        FOLDER: gh-page
        SINGLE-COMMIT: true
